[window]
opacity = 0.9

[window.padding]
x = 6
y = 6

[cursor]
style.shape = "Underline"
style.blinking = "On"
blink_interval = 500

[font]
normal = { family = "JetBrainsMono Nerd Font Propo", style = "Regular" }
size = 10

[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#2E3440"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"
